version: '3.7'
  services:
    backend:
      image: codevid/backend:latest
      build:
        context: .
        dockerfile: spring-petclinic-rest/Dockerfile
      ports:
        - target: 9966
          published: 9966
          protocol: tcp
    frontend:
      image: codevid/frontend:latest
      build:
        context: .
        dockerfile: spring-petclinic-angular/Dockerfile
      ports:
        - target: 8080
          published: 8080
          protocol: tcp